// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHAoZBHZj0b2YV9EdfGkwBkSTZlUrQL_k',
    appId: '1:101841636395:web:48e762747e8db0aa5cae6e',
    messagingSenderId: '101841636395',
    projectId: 'nute-auto',
    authDomain: 'nute-auto.firebaseapp.com',
    databaseURL: 'https://nute-auto-default-rtdb.firebaseio.com',
    storageBucket: 'nute-auto.appspot.com',
    measurementId: 'G-VMMP21GBCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQINtEOdqo-sLt8gxwOUSyv2JyRvntO4I',
    appId: '1:101841636395:android:290254e4b14506d35cae6e',
    messagingSenderId: '101841636395',
    projectId: 'nute-auto',
    databaseURL: 'https://nute-auto-default-rtdb.firebaseio.com',
    storageBucket: 'nute-auto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmrllrOGAhlBhA2Jfg7zvgx5RZISJqElE',
    appId: '1:101841636395:ios:d8014f47c72a7e325cae6e',
    messagingSenderId: '101841636395',
    projectId: 'nute-auto',
    databaseURL: 'https://nute-auto-default-rtdb.firebaseio.com',
    storageBucket: 'nute-auto.appspot.com',
    iosBundleId: 'com.anutesapplication.app.testProject',
  );
}
